### ISSUE TITLE
Fatal error: [] operator not supported for strings in 

### ISSUE THREAD

**Issue by BlackWireDesigns** [bainternet/GWP-mail-BCC-and-CC#1]
Hello. 

Any idea what would be causing this issue

Fatal error: [] operator not supported for strings in /wordpress/htdocs/wp-content/plugins/GWP-mail-BCC-and-CC-master/gwp_bcc_cc_mail.php on line 50

This is line 50 from the php file

```
                    $args['headers'][] = 'Cc: '.trim($cc_address);
```

**Comment by nyedidikeke** [comment]
Surely, your PHP version must be lower than 5.4 because `[]` (the short array syntax for `array()`) was introduced as of that version.
*You may read more [here](https://secure.php.net/manual/en/language.types.array.php 'PHP Manual; array definition, syntax and examples') and [here](https://secure.php.net/manual/en/migration54.new-features.php 'New features (PHP 5.4)').*

**Comment by nyedidikeke** [comment]
Surely, your PHP version must be lower than 5.4 because `[]`, the short array syntax for `array()`, was introduced as of that version.
*You may read more [here](https://secure.php.net/manual/en/language.types.array.php 'PHP Manual; array definition, syntax and examples') and [here](https://secure.php.net/manual/en/migration54.new-features.php 'New features (PHP 5.4)').*

**Comment by nyedidikeke** [comment]
Surely, your PHP version **must** be lower than 5.4 because `[]` (the short array syntax for `array()`) was introduced as of that version.
*You may read more [here](https://secure.php.net/manual/en/language.types.array.php 'PHP Manual; array definition, syntax and examples') and [here](https://secure.php.net/manual/en/migration54.new-features.php 'New features (PHP 5.4)').*

**Comment by nyedidikeke** [comment]
Surely, your PHP version **must** be lower than 5.4 because `[]`, the short array syntax for `array()`, was introduced as of that version.
*You may read more [here](https://secure.php.net/manual/en/language.types.array.php 'PHP Manual; array definition, syntax and examples') and [here](https://secure.php.net/manual/en/migration54.new-features.php 'New features (PHP 5.4)').*

**Comment by giftsurplus** [comment]
I get the same results on PHP 5.6.30
